package com.job.thread;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;

import com.jeeplus.common.config.Global;

public class WxNickImgUtils {
	public static String[] nicknames={
		"琴弦泪",
		"浅吻＠",
		"天真无鞋",
		"初夏の雨 ﹌",
		"疯子范ル",
		"戒烟戒酒不戒你ぃ",
		"泪颜葬相思",
		"ぅ骚动的青春'",
		"滥人情 Triste 。",
		"姓大名爷",
		"虐心少年。",
		"- 年少梦未了 //*",
		"若是梦 终将空 #",
		"当幸福来敲门，我却不在家",
		"一见钟情不过是见色起意ヾ",
		"我想找你,却没了借口",
		"最凉卜过人心╮",
		"老师、比卫生纸都能扯",
		"孤独患者，久病成医",
		"℡笑颜如花◎",
		"别在我眼前犯贱",
		"微笑掩盖不了泪痕~",
		"回忆总是虐心菂ノ",
		"溺于你心海 ,",
		"入戏太深、失了分寸 ♢",
		"- 情若能自控°",
		"空城里的亡命徒",
		"゛愈爱愈痛ぃ",
		"良言未素，",
		"凉薄骚年BUWANXIN",
		"空有一丝愁°ˉ",
		"释怀° Believeヾ",
		"童色安年*",
		"temperature ° 浅陌",
		"________花祭。",
		"旧言虐心ˇ Person",
		"- 除了心跳什么都忘掉。",
		"时光滥好人*",
		"旧人不覆 °",
		"″ 一纸荒凉 。",
		"_过去,怎么过去/",
		"心不动 则不痛丶",
		"正儿八经的小骚年°",
		"孤魂一缕尤牵挂",
		"梦到醒不来的梦*",
		"不配拥有爱情丶",
		"我不是谁的代替品..°",
		"♬ 为你存在才不孤单",
		"沫忆失忆丶",
		"是谁惹谁言不由衷*",
		"难以抗拒的温柔 。",
		"曾经′我以为是梦。",
		"烂人烂心烂世界・",
		"我只对你一人难缠 。",
		"在美的记忆也是过去°",
		"看爱情在演戏*",
		"-说了再见也没用",
		"仅一心 °",
		"少年滥情不花心ぅ",
		"逆风飞行更适合成长",
		"除了坚强、别无选择",
		"改变是痛苦，不改变是受苦",
		"认栽认亏不认输",
		"天生傲骨、怎能屈服",
		"不努力你什么都不是",
		"没死就别把自己当废物",
		"[有梦才不怕痛]",
		"自己选的路跪著也ｙāō走完",
		"梦想的天空分外蓝",
		"菇凉，活出你的高姿态来",
		"天会亮心会暖i",
		"羡慕别人不如做好自己",
		"铁骨铮铮女子汉",
		"透过骨zǐ里的傲气つ",
		"黄瓜必须拍人生必须嗨",
		"别让梦枯萎",
		"再苦再痛也别忘了微笑i",
		"命由天事在己",
		"一击就碎的念头不是梦想",
		"後悔過去不如奮鬥將來",
		"青春之帆由我掌舵",
		"不努力，拿什么说明天",
		"薄荷绿°",
		"北城以念·何以为安",
		"淚幹了以後、繼續走",
		"不努力梦想永远只是梦",
		"姓坚名强没死就能继续辉煌",
		"梦想起航我起床",
		"梦想注定是孤独的旅行",
		"莫欺少年穷",
		"背着书包闯天下",
		"命由己造",
		"一无所有就是拼的理由",
		"前路坎坷不言弃つ",
		"阳光总在风雨后",
		"奋斗吧〆少年°",
		"每一种痛都是一种成熟",
		"少壮不努力，长大抢小米",
		"时间不会说谎",
		"允我心安"
	};
	
	public static String[] headimgs={
		"img (1).jpg",
		"img (2).jpg",
		"img (3).jpg",
		"img (4).jpg",
		"img (5).jpg",
		"img (6).jpg",
		"img (7).jpg",
		"img (8).jpg",
		"img (9).jpg",
		"img (10).jpg",
		"img (11).jpg",
		"img (12).jpg",
		"img (13).jpg",
		"img (14).jpg",
		"img (15).jpg",
		"img (16).jpg",
		"img (17).jpg",
		"img (18).jpg",
		"img (19).jpg",
		"img (20).jpg",
		"img (21).jpg",
		"img (22).jpg",
		"img (23).jpg",
		"img (24).jpg",
		"img (25).jpg",
		"img (26).jpg",
		"img (27).jpg",
		"img (28).jpg",
		"img (29).jpg",
		"img (30).jpg",
		"img (31).jpg",
		"img (32).jpg",
		"img (33).jpg",
		"img (34).jpg",
		"img (35).jpg",
		"img (36).jpg",
		"img (37).jpg",
		"img (38).jpg",
		"img (39).jpg",
		"img (40).jpg",
		"img (41).jpg",
		"img (42).jpg",
		"img (43).jpg",
		"img (44).jpg",
		"img (45).jpg",
		"img (46).jpg",
		"img (47).jpg",
		"img (48).jpg",
		"img (49).jpg",
		"img (50).jpg",
		"img (51).jpg",
		"img (52).jpg",
		"img (53).jpg",
		"img (54).jpg",
		"img (55).jpg",
		"img (56).jpg",
		"img (57).jpg",
		"img (58).jpg",
		"img (59).jpg",
		"img (60).jpg",
		"img (61).jpg",
		"img (62).jpg",
		"img (63).jpg",
		"img (64).jpg",
		"img (65).jpg",
		"img (66).jpg",
		"img (67).jpg",
		"img (68).jpg",
		"img (69).jpg",
		"img (70).jpg",
		"img (71).jpg",
		"img (72).jpg",
		"img (73).jpg",
		"img (74).jpg",
		"img (75).jpg",
		"img (76).jpg",
		"img (77).jpg",
		"img (78).jpg",
		"img (79).jpg",
		"img (80).jpg",
		"img (81).jpg",
		"img (82).jpg",
		"img (83).jpg",
		"img (84).jpg",
		"img (85).jpg",
		"img (86).jpg",
		"img (87).jpg",
		"img (88).jpg",
		"img (89).jpg",
		"img (90).jpg",
		"img (91).jpg",
		"img (92).jpg",
		"img (93).jpg",
		"img (94).jpg",
		"img (95).jpg",
		"img (96).jpg",
		"img (97).jpg",
		"img (98).jpg",
		"img (99).jpg",
		"img (100).jpg"
	};
}
